### PR TITLE
Feature3 branch

### PR DESCRIPTION
**Pull request by AnshulGoyal589**
I have added the Navbar and added A Dark and Light Mode toggle on the navbar  
Closes issue #5 

please accept it under hactoberfest 2023.

### CODE REVIEW

**Comment by karantec** [comment]
Responsive error issues

**Comment by AnshulGoyal589** [comment]
@karantec please check now, i have updated the PR, and if there is any other issue still existing, please let me know

**Comment by karantec** [comment]
Okay

**Comment by AnshulGoyal589** [comment]
@karantec  if there is no issue, please accept it under hactoberfest 2023 and merge it

**Comment by karantec** [comment]
ya sure

**Comment by AnshulGoyal589** [comment]
@karantec hope changes made are good, please merge this PR so that it can be counted in my hactoberfest 2023 PR
and please label it as hactoberfest , hactoberfest-accepted

**Comment by AnshulGoyal589** [comment]
> @karantec hope changes made are good, please merge this PR so that it can be counted in my hactoberfest 2023 PR and please label it as hactoberfest , hactoberfest-accepted

@karantec

**Comment by karantec** [comment]
let me check after the meeting

**Comment by AnshulGoyal589** [comment]
sure

**Comment by AnshulGoyal589** [comment]
@karantec please merge my PR with label of hactoberfest

**Comment by karantec** [comment]
Ya I got free today sorry I am busy in work I will review it and merge it
today

**Comment by karantec** [comment]
nice work I have another repo

**Pull request merged**
