### PR TITLE
Feat/#10 tailwindcss added

### PR DESCRIPTION
**Pull request by kunal-511**
In this update, a significant enhancement has been made to the project's frontend design by transitioning to the popular CSS framework, Tailwind CSS. This change brings a fresh and modern look to the application, leveraging Tailwind CSS's utility-first approach for rapid and customizable styling. With Tailwind CSS, the project benefits from a more efficient and flexible styling workflow, allowing for quicker development and easier maintenance. Users can now experience a visually appealing and responsive user interface that aligns with contemporary design standards. This update not only improves the aesthetics but also enhances the overall user experience, making the application more user-friendly and visually appealing.

### CODE REVIEW

**Comment by kunal-511** [comment]
i have added required tailwind css please review and merge it

**Comment by karantec** [comment]
sure

**Comment by kunal-511** [comment]
please merge or tell if any issue is their?

**Comment by kunal-511** [comment]
Please merge this to main branch

**Comment by karantec** [comment]
ya let me see

**Comment by karantec** [comment]
the issue has solved already by another person
https://meme-generate-beryl.vercel.app/

**Comment by karantec** [comment]
Issue closed

**Comment by karantec** [comment]
you can work on it
 I have another app that if gif generator it will be ready in night and
uploaded it to GitHub today  , so if you want to work on this social media
button issue you can work .

**Comment by kunal-511** [comment]
ok

**Pull request closed without merging**
