### PR TITLE
Made it Responsive for Mobile View

### PR DESCRIPTION
**Pull request by madm234**
### Made it responsive for width screen less than 600px or mobile view. See attached images.
WhatsApp Image 2023-10-09 at 23 25 16_3a30f67f

WhatsApp Image 2023-10-09 at 23 25 16_08d1d9bb

### CODE REVIEW

**Comment by madm234** [comment]
I'm right here if you want any changes or modifications in this.

**Comment by madm234** [comment]
Please merge it under hactoberfest.

**Comment by karantec** [comment]
Ya sure

**Comment by madm234** [comment]
@karantec Just a small reminder to merge this pr. Ignore if u are busy.

**Comment by karantec** [comment]
Sure thanks for reminding me

**Comment by madm234** [comment]
Sorry man to disturb you everyday.

**Comment by karantec** [comment]
No yaar as a maintainer I have to see that also

**Comment by madm234** [comment]
> No yaar as a maintainer I have to see that also

Karan bhai just a remainder.

**Comment by karantec** [comment]
Done Bhai

**Pull request merged**
